[package]
name = "symcas"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "symcas: Fast, deterministic computer algebra system in Rust"
readme = "README.md"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
cas-domain = { workspace = true }
cas-expr = { workspace = true }
cas-print = { workspace = true }
cas-parse = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
cas-expr = { version = "0.1.0", path = "../../crates/expr", features = ["test-gen"] }
