[package]
name = "cas-poly"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "cas-poly: Ordered sparse distributed multivariate polynomials generic over coefficient rings"
readme = "README.md"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
cas-domain = { workspace = true }
