[package]
name = "cas-print"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "cas-print: Plain roundtrip and LaTeX formatting for symcas expressions"
readme = "README.md"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
cas-expr = { workspace = true }
cas-domain = { workspace = true }
