[package]
name = "cas-parse"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "cas-parse: Recursive descent parser for symcas plain grammar with roundtrip guarantee"
readme = "README.md"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
cas-expr = { workspace = true }
cas-domain = { workspace = true }

[dev-dependencies]
cas-print = { workspace = true }
